---
title: "Tibbles with tibble"
output: html_notebook
---

```{r}
vignette('tibble')
library(tidyverse)
```
Creating tibbles
```{r}
typeof(iris)
as.tibble(iris)
typeof(as.tibble(iris))

#create new tibble from individual vectors
tibble(
  x=  1:5,
  y = 1,
  z = x^2 + y
)

#tibble does not change the types of input
#it is possible for tibble to create column names that are not valid in R
tb = tibble(
  ':)' = 'smile',
  ' ' = 'space',
  '2000' = 'number'
)

#another way in creating tibble is tribble() short for tranposed tibble. tribble is customized for data entry in code. colum headings are defined by formulas and entries are separated by commas. 
tribble(
  ~x, ~y, ~z,
  #--------
  'a',2,3.6,
  'b',3,5
)

```

Tibbles vs dataframe - two main differences are printing and subsetting
```{r}
tibble(
  a = lubridate::now() + runif(1e3) * 86400,
  b = lubridate::today() + runif(1e3) * 30,
  c = 1:1e3,
  d = runif(1e3),
  e = sample(letters, 1e3, replace = T)
)

#tibbles are designed so that you dont accidentally overwhelm your console when you print large dataframes. Sometimes you need more output that default display. 

#you can explicitly print() and control the number of rows(n) and the width(= inf)
nycflights13::flights %>%
  print(n = 10, width = Inf)

#can control the default print behavior using these options
options(tibble.print_max = n, tibble.print_min = m)
options(dplyr.print_min = Inf) # to always show all rows
options(tibble.width = Inf) # to always print all columns

?tibble

#final option is to use Rstudio complete dataset
nycflights13::flights %>%
  View()
```

Subsetting
```{r}
df = tibble(
  x = runif(5),
  y = rnorm(5)
)

#extract by name
df$x
df[['x']]

#extract by position
df[[1]]

#to use in a pipe
df %>%
  .$x

df %>%
  .[['x']]
```

Interacting with older code
```{r}
#some older functions dont work on tibbles if you encounter these problems use as.data.frame() to convert tibble back to dataframe

class(as.data.frame(tb))
```

Exercises
```{r}
#how to tell if an object is tibble
mtcars
mt_tibble = as.tibble(mtcars)
mt_tibble

print(mtcars)
#use istibble to check if it is a tibble
is_tibble(mtcars)


#2. compare and contrast the following operations on a data.frame and equivalent tibble. What is different, Why might the default frame behaviors cause you frustration

df = data.frame(abc = 1, xyz = 'a')
df$x
class(df[,'xyz'])
df[,c('abc','xyz')]

dft = as.tibble(df)
dft$x
class(dft[,'xyz'])
df[,c('abc','xyz')]

#3. if you have the name of a variable stored in an object, how can you extract reference variable from a tibble
var = 'hwy'
mpg[[var]]
mpg$var

#4. practice
annoying <- tibble(
  `1` = 1:10,
  `2` = `1` * 2 + rnorm(length(`1`))
)

#extracting variable 1
annoying$`1`
annoying[['1']]
annoying[,'1']

#plotting scatterplot of 1 vs 2
ggplot(annoying, aes(x = `1`, y = `2`)) +
  geom_point()

#create new column 3 which is 2 divide 1
annoying %>%
  mutate(`3` = `2`/`1`)

annoying['3'] = annoying[['2']]/annoying[['1']]
annoying$'3'

#rename columns to one two three
annoying = rename(annoying, 'one' = 1, 'two' = 2, 'three' = 3)

#what does enframe do?
?enframe
enframe(1:4)
```














